
package sf.crom.sf.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Sun Aug 28 19:14:39 CDT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://services.sf.crom.sf/", name = "PaymentProcess")

public interface PaymentProcess {

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "createPaymentProcess", targetNamespace = "http://services.sf.crom.sf/", className = "sf.crom.sf.services.CreatePaymentProcess")
    @ResponseWrapper(localName = "createPaymentProcessResponse", targetNamespace = "http://services.sf.crom.sf/", className = "sf.crom.sf.services.CreatePaymentProcessResponse")
    @WebMethod
    public sf.crom.sf.services.PaymentProcessResponse createPaymentProcess(
        @WebParam(name = "PaymentProcessRequest", targetNamespace = "")
        sf.crom.sf.services.PaymentProcessRequest paymentProcessRequest
    );
}
